--  ╭──────────────────────────────────────────────────────────╮
--  │ Marty Buchaus Neovim Configuration                       │
--  ╰──────────────────────────────────────────────────────────╯

return {
    -- 'MeanderingProgrammer/render-markdown.nvim',
    -- dependencies = { 
    --     'nvim-treesitter/nvim-treesitter', 
    --     'nvim-tree/nvim-web-devicons' 
    -- },
    -- ft = { 'markdown' },
    -- cmd = {
    --     "RenderMarkdown",
    -- },
    -- opts = {
    --     render_modes = { 'n', 'v', 'i', 'c' },
    --     injections = {
    --         gitcommit = {
    --             enabled = true,
    --             query = [[
    --             ((message) @injection.content
    --                 (#set! injection.combined)
    --                 (#set! injection.include-children)
    --                 (#set! injection.language "markdown"))
    --         ]],
    --         },
    --     },
    --     heading = {
    --         enabled = true,
    --         sign = true,
    --         position = 'overlay',
    --         icons = { '󰲡 ', '󰲣 ', '󰲥 ', '󰲧 ', '󰲩 ', '󰲫 ' },
    --         signs = { '󰫎 ' },
    --         width = 'full',
    --         left_pad = 0,
    --         right_pad = 0,
    --         min_width = 0,
    --         border = false,
    --         border_prefix = false,
    --         above = '▄',
    --         below = '▀',
    --         backgrounds = {
    --             'RenderMarkdownH1Bg',
    --             'RenderMarkdownH2Bg',
    --             'RenderMarkdownH3Bg',
    --             'RenderMarkdownH4Bg',
    --             'RenderMarkdownH5Bg',
    --             'RenderMarkdownH6Bg',
    --         },
    --         foregrounds = {
    --             'RenderMarkdownH1',
    --             'RenderMarkdownH2',
    --             'RenderMarkdownH3',
    --             'RenderMarkdownH4',
    --             'RenderMarkdownH5',
    --             'RenderMarkdownH6',
    --         },
    --     },
    --
    --     indent = {
    --         enabled = true,
    --         per_level = 2,
    --         skip_level = 1,
    --         skip_heading = true,
    --     },
    --
    --     callout = {
    --         note = { raw = '[!NOTE]', rendered = '󰋽 Note', highlight = 'RenderMarkdownInfo' },
    --         tip = { raw = '[!TIP]', rendered = '󰌶 Tip', highlight = 'RenderMarkdownSuccess' },
    --         important = { raw = '[!IMPORTANT]', rendered = '󰅾 Important', highlight = 'RenderMarkdownHint' },
    --         warning = { raw = '[!WARNING]', rendered = '󰀪 Warning', highlight = 'RenderMarkdownWarn' },
    --         caution = { raw = '[!CAUTION]', rendered = '󰳦 Caution', highlight = 'RenderMarkdownError' },
    --         -- Obsidian: https://help.obsidian.md/Editing+and+formatting/Callouts
    --         abstract = { raw = '[!ABSTRACT]', rendered = '󰨸 Abstract', highlight = 'RenderMarkdownInfo' },
    --         summary = { raw = '[!SUMMARY]', rendered = '󰨸 Summary', highlight = 'RenderMarkdownInfo' },
    --         tldr = { raw = '[!TLDR]', rendered = '󰨸 Tldr', highlight = 'RenderMarkdownInfo' },
    --         info = { raw = '[!INFO]', rendered = '󰋽 Info', highlight = 'RenderMarkdownInfo' },
    --         todo = { raw = '[!TODO]', rendered = '󰗡 Todo', highlight = 'RenderMarkdownInfo' },
    --         hint = { raw = '[!HINT]', rendered = '󰌶 Hint', highlight = 'RenderMarkdownSuccess' },
    --         success = { raw = '[!SUCCESS]', rendered = '󰄬 Success', highlight = 'RenderMarkdownSuccess' },
    --         check = { raw = '[!CHECK]', rendered = '󰄬 Check', highlight = 'RenderMarkdownSuccess' },
    --         done = { raw = '[!DONE]', rendered = '󰄬 Done', highlight = 'RenderMarkdownSuccess' },
    --         question = { raw = '[!QUESTION]', rendered = '󰘥 Question', highlight = 'RenderMarkdownWarn' },
    --         help = { raw = '[!HELP]', rendered = '󰘥 Help', highlight = 'RenderMarkdownWarn' },
    --         faq = { raw = '[!FAQ]', rendered = '󰘥 Faq', highlight = 'RenderMarkdownWarn' },
    --         attention = { raw = '[!ATTENTION]', rendered = '󰀪 Attention', highlight = 'RenderMarkdownWarn' },
    --         failure = { raw = '[!FAILURE]', rendered = '󰅖 Failure', highlight = 'RenderMarkdownError' },
    --         fail = { raw = '[!FAIL]', rendered = '󰅖 Fail', highlight = 'RenderMarkdownError' },
    --         missing = { raw = '[!MISSING]', rendered = '󰅖 Missing', highlight = 'RenderMarkdownError' },
    --         danger = { raw = '[!DANGER]', rendered = '󱐌 Danger', highlight = 'RenderMarkdownError' },
    --         error = { raw = '[!ERROR]', rendered = '󱐌 Error', highlight = 'RenderMarkdownError' },
    --         bug = { raw = '[!BUG]', rendered = '󰨰 Bug', highlight = 'RenderMarkdownError' },
    --         example = { raw = '[!EXAMPLE]', rendered = '󰉹 Example', highlight = 'RenderMarkdownHint' },
    --         quote = { raw = '[!QUOTE]', rendered = '󱆨 Quote', highlight = 'RenderMarkdownQuote' },
    --         cite = { raw = '[!CITE]', rendered = '󱆨 Cite', highlight = 'RenderMarkdownQuote' },
    --     },
    --
    --     bullet = {
    --         enabled = true,
    --         icons = { '●', '○', '◆', '◇' },
    --         left_pad = 0,
    --         right_pad = 1,
    --         highlight = 'RenderMarkdownBullet',
    --     },
    --
    --     pipe_table = {
    --         enabled = true,
    --         preset = 'normal',
    --         style = 'full',
    --         cell = 'padded',
    --         min_width = 0,
    --         border = {
    --             '┌', '┬', '┐',
    --             '├', '┼', '┤',
    --             '└', '┴', '┘',
    --             '│', '─',
    --         },
    --         alignment_indicator = '━',
    --         head = 'RenderMarkdownTableHead',
    --         row = 'RenderMarkdownTableRow',
    --         filler = 'RenderMarkdownTableFill',
    --     },
    --
    --     checkbox = {
    --         enabled = true,
    --         position = 'inline',
    --         unchecked = {
    --             icon = '󰄱 ',
    --             highlight = 'RenderMarkdownUnchecked',
    --         },
    --         checked = {
    --             icon = " ",
    --             highlight = 'RenderMarkdownChecked',
    --         },
    --         custom = {
    --             todo = { raw = '[-]', rendered = '󰥔 ', highlight = 'RenderMarkdownTodo' },
    --             started = { raw = "[>]", rendered = " ", highlight = "@markup.raw" },
    --             deleted = { raw = "[~]", rendered = " ", highlight = "@markup.raw" },
    --         },
    --     },
    --
    --     dash = {
    --         enabled = true,
    --         icon = '─',
    --         width = 'full',
    --         highlight = 'RenderMarkdownDash',
    --     },
    -- },
}
