--  ╭──────────────────────────────────────────────────────────╮
--  │ Marty Buchaus Neovim Configuration                       │
--  ╰──────────────────────────────────────────────────────────╯

return {
    -- "vimwiki/vimwiki",
    -- dependencies = {
    --     "mattn/calendar-vim",
    --     "tools-life/taskwiki",
    --     "michal-h21/vim-zettel",
    -- },
    -- cmd = { 
    --     "VimwikiIndex", 
    --     "VimwikiDiaryIndex",
    --     "VimwikiMakeDiaryNote",
    --     "ZettelSearch" },
    -- keys = {
    --     { "<leader>nw", "<cmd>VimwikiIndex<cr>", desc = "Open Vimwiki Index" },
    --     { "<leader>ni", "<Plug>VimwikiIndex", desc = "Vimwiki Index" },
    --     { "<leader>ns", "<Plug>VimwikiUISelect", desc = "Vimwiki Select" },
    --     { "<leader>nt", "<Plug>VimwikiTabIndex", desc = "Vimwiki Tab Index" },
    --     { "<leader>nd", "<Plug>VimwikiMakeDiaryNote", desc = "Vimwiki Diary Today" },
    --     { "<leader>nD", "<Plug>VimwikiDiaryIndex", desc = "Vimwiki Diary Index" },
    --     { "<leader>nn", "<Plug>VimwikiDiaryGenerateLinks", desc = "Vimwiki Generate Diary Links" },
    --     { "<leader>nr", "<Plug>VimwikiRenameFile", desc = "Vimwiki Rename File" },
    --     { "<leader>nb", "<Plug>VimwikiGoBackLink", desc = "Vimwiki Go Back Link" },
    --     { "<leader>nh", "<Plug>Vimwiki2HTML", desc = "Vimwiki Convert to HTML" },
    --     { "<leader>nz", "<cmd>ZettelSearch<cr>", desc = "Zettelkasten Search" },
    --     { "<leader>nl", "i[[<C-r>=expand('%:t:r')<CR>]]<Esc>",  desc = "Insert Vimwiki Link" }
    -- },
    -- init = function()
    --     vim.g.vimwiki_list = {
    --         {
    --             path = "~/Nextcloud/Notes",
    --             syntax = "markdown",
    --             ext = ".md",
    --         },
    --     }
    --     vim.g.vimwiki_ext2syntax = { [".md"] = "markdown" }
    --     vim.g.vimwiki_global_ext = 0
    --     vim.g.vimwiki_key_mappings = { all_maps = 0 }
    --     vim.g.taskwiki_markup_syntax = "markdown"
    --     vim.g.zettel_format = "%y%m%d%H%M%S"
    --     vim.g.zettel_fzf_command = "fzf"
    -- end,
}
